import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const base = process.env.MCMS_UI_URL || 'http://127.0.0.1:5173';
const output = process.env.MCMS_QA_DIR || './qa';
await mkdir(output, {recursive:true});
const browser = await chromium.launch({headless:true, channel:'chrome'});
const page = await browser.newPage({viewport:{width:1512,height:1000},deviceScaleFactor:1});
const errors=[];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(base, {waitUntil:'domcontentloaded', timeout:60000});
  await page.getByLabel('Email', {exact:true}).fill('admin@coalchain.local');
  await page.getByLabel('Password', {exact:true}).fill(process.env.MCMS_UI_PASSWORD || 'CoalChain-Local-2026!');
  await page.getByRole('button', {name:'Masuk ke workspace'}).click();
  await page.getByRole('heading', {name:'Operation control tower',exact:true}).waitFor();
  await page.getByText('Coal production', {exact:true}).waitFor();
  await page.screenshot({path:output+'/desktop.png',fullPage:true});
  assert.ok(await page.locator('.kpi-card').count()===4);
  assert.equal(await page.locator('.sidebar').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(37, 60, 109)');
  await page.locator('.sidebar').getByRole('button',{name:'Pengaturan',exact:true}).click();
  await page.getByRole('heading',{name:'Branding aplikasi',exact:true}).waitFor();
  await page.getByLabel('Nama aplikasi',{exact:true}).fill('CoalChain UI QA');
  await page.getByLabel('Label operasional',{exact:true}).fill('OWNER CONTROL');
  await page.getByRole('button',{name:'Simpan branding',exact:true}).click();
  await page.getByText('CoalChain UI QA',{exact:true}).first().waitFor();
  await page.locator('.sidebar').getByRole('button',{name:'Control tower',exact:true}).click();
  await page.locator('.segmented').getByRole('button',{name:'Overburden',exact:true}).click();
  assert.equal(await page.locator('.chart svg').getAttribute('aria-label'),'Grafik produksi ob per hari');
  await page.locator('.sidebar').getByRole('button',{name:'Daily production',exact:true}).click();
  await page.locator('tbody tr').first().waitFor();
  await page.getByLabel('Cari transaksi').fill('DOES-NOT-EXIST');
  await page.getByRole('heading',{name:'Tidak ada data yang sesuai'}).waitFor();
  await page.getByLabel('Cari transaksi').fill('');
  await page.locator('tbody tr').first().waitFor();
  await page.locator('.sidebar').getByRole('button',{name:'HSE & safety',exact:true}).click();
  await page.getByRole('button',{name:'Tambah data',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('Site', {exact:false}).selectOption({index:1});
  await dialog.getByLabel('Kontraktor', {exact:false}).selectOption({index:1});
  await dialog.getByLabel('Jenis kejadian').selectOption('Safety Observation');
  const marker='UI QA '+Date.now();
  await dialog.getByLabel('Lokasi',{exact:false}).fill('Workshop test');
  await dialog.getByLabel('Deskripsi',{exact:false}).fill(marker);
  await dialog.getByLabel('Tindakan korektif',{exact:false}).fill('Pemeriksaan terjadwal dan dokumentasi.');
  await dialog.getByRole('button',{name:'Simpan data',exact:true}).click();
  await dialog.waitFor({state:'hidden'});
  await page.getByLabel('Cari transaksi').fill(marker);
  await page.locator('tbody .record-link').first().click();
  await dialog.getByRole('button',{name:'Dokumen (0)',exact:true}).click();
  await dialog.locator('input[type=file]').setInputFiles({name:'ui-evidence.txt',mimeType:'text/plain',buffer:Buffer.from('UI attachment verification')});
  await dialog.getByText('ui-evidence.txt',{exact:true}).waitFor();
  await dialog.getByRole('button',{name:'Detail',exact:true}).click();
  await dialog.screenshot({path:output+'/detail.png'});
  await dialog.getByRole('button',{name:'Submit approval'}).click();
  await dialog.getByRole('button',{name:'Approve tahap 1'}).click();
  await dialog.getByRole('button',{name:'Approve tahap 2'}).click();
  await dialog.locator('.detail-top .badge.approved').waitFor();
  await dialog.getByRole('button',{name:'Tutup dialog'}).click();
  await page.locator('.sidebar').getByRole('button',{name:'Control tower',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:output+'/mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No page-wide mobile overflow');
  await page.getByRole('button',{name:'Buka menu'}).click();
  await page.locator('.sidebar').getByRole('button',{name:'Fuel management',exact:true}).click();
  await page.getByRole('heading',{name:'Fuel management',exact:true}).waitFor();
  assert.equal(await page.locator('.sidebar.open').count(),0);
  await page.getByRole('button',{name:'Tambah data',exact:true}).click();
  assert.equal(await page.getByRole('dialog').isVisible(),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(),0);
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop/mobile, login, dashboard chart, search, HSE create, document upload, approval workflow, responsive navigation, keyboard dialog.');
} finally {await browser.close();}

