"""Form contracts shared by API validation and the React client."""

def field(key, label, kind="text", required=True, options=None, ref=None):
    return {"key": key, "label": label, "type": kind, "required": required, "options": options or [], "ref": ref}

def module(label, group, fields, columns, writers, workflow=None):
    return dict(label=label, group=group, fields=fields, columns=columns, writers=writers,
                workflow=workflow or [])

ADMIN = "System Administrator"
ROLES = [ADMIN, "Mining Operation", "Mine Engineering", "Surveyor", "Dispatch", "Fuel Controller", "HSE",
         "Contractor User", "Contractor Supervisor", "Owner Supervisor", "Commercial", "Procurement", "Finance",
         "Mine Manager", "General Manager", "Director", "Auditor"]
CONTRACTOR_ROLES = ["Contractor User", "Contractor Supervisor"]
OPS = ["Mining Operation", "Dispatch", *CONTRACTOR_ROLES]
DATE = field("date", "Tanggal", "date")
SITE = field("site_id", "Site", "reference", ref="sites")
CONTRACTOR = field("contractor_id", "Kontraktor", "reference", ref="contractors")
PIT = field("pit_id", "Pit", "reference", ref="pits")
ACTIVITIES = ["OB Removal", "Topsoil Removal", "Coal Getting", "Coal Hauling", "OB Hauling", "Road Maintenance", "Dewatering", "Land Clearing", "Rehabilitation", "Supporting Work"]
ACTIVITY = field("activity", "Aktivitas", "select", options=ACTIVITIES)
QUANTITY = field("quantity", "Quantity", "number")
UNIT = field("unit", "Satuan", "select", options=["BCM", "Ton", "Ton-KM", "BCM-KM", "Hour", "Month"])
EQUIPMENT = field("equipment_id", "Equipment", "reference", ref="equipment")
PERIOD = field("period", "Periode", "month")
CONTRACT = field("contract_id", "Kontrak", "reference", ref="contracts")
SHIFT = field("shift", "Shift", "select", options=["Day", "Night"])

CATALOG = {
 "sites": module("Site & organisasi", "Master Data", [field("name", "Nama site"), field("company", "Perusahaan"), field("location", "Lokasi")], ["name", "company", "location"], ["Mine Engineering"]),
 "pits": module("Pit & area", "Master Data", [field("name", "Nama pit"), SITE, field("area", "Mining area"), field("block", "Block"), field("seam", "Seam", required=False)], ["name", "site_id", "area", "block"], ["Mine Engineering"]),
 "locations": module("Lokasi & rute", "Master Data", [field("name", "Nama lokasi"), SITE, field("type", "Jenis", "select", options=["Stockpile", "Disposal", "Hauling Route", "Workshop", "Fuel Station", "ROM", "Port", "Jetty", "River Terminal"]), field("distance", "Jarak (km)", "number", False)], ["name", "site_id", "type", "distance"], ["Mine Engineering", "Dispatch"]),
 "contractors": module("Kontraktor", "Master Data", [field("name", "Nama kontraktor"), field("vendor_id", "Vendor ID"), SITE, field("address", "Alamat", required=False), field("contact", "Kontak"), field("owner_pic", "PIC owner"), field("contractor_pic", "PIC kontraktor")], ["name", "vendor_id", "site_id", "contact"], ["Procurement"]),
 "contracts": module("Kontrak", "Commercial", [field("name", "Nomor kontrak"), CONTRACTOR, SITE, field("type", "Jenis kontrak", "select", options=["Mining Services", "Hauling", "Equipment Rental", "Supporting Work"]), field("start", "Mulai", "date"), field("end", "Berakhir", "date"), field("value", "Nilai kontrak (Rp)", "number"), field("quantity_limit", "Batas quantity", "number"), field("scope", "Lingkup pekerjaan", "textarea"), field("payment_terms", "Termin pembayaran"), field("retention", "Retensi (%)", "number")], ["name", "contractor_id", "value", "end", "status"], ["Procurement", "Commercial"], ["Commercial", "Mine Manager"]),
 "rates": module("Rate kontrak", "Commercial", [CONTRACT, CONTRACTOR, SITE, ACTIVITY, UNIT, field("rate", "Rate (Rp)", "number"), field("start", "Efektif mulai", "date"), field("end", "Efektif sampai", "date"), field("min_distance", "Jarak minimum (km)", "number"), field("max_distance", "Jarak maksimum (km)", "number")], ["contract_id", "activity", "unit", "rate", "status"], ["Commercial"], ["Commercial"]),
 "amendments": module("Amendment", "Commercial", [CONTRACT, CONTRACTOR, SITE, field("value_change", "Perubahan nilai (Rp)", "signed"), field("quantity_change", "Perubahan batas quantity", "signed"), field("new_end", "Tanggal akhir baru", "date"), field("reason", "Alasan", "textarea")], ["contract_id", "value_change", "new_end", "status"], ["Commercial", "Procurement"], ["Commercial", "Mine Manager"]),
 "plans": module("Mining plan", "Operations", [field("name", "Nama rencana"), SITE, PIT, CONTRACTOR, ACTIVITY, field("level", "Level", "select", options=["Life of Mine", "Annual", "Monthly", "Weekly", "Daily"]), field("start", "Mulai", "date"), field("end", "Selesai", "date"), QUANTITY, UNIT, field("budget", "Budget (Rp)", "number")], ["name", "contractor_id", "activity", "quantity", "status"], ["Mine Engineering"], ["Mine Manager"]),
 "equipment": module("Equipment & fleet", "Operations", [field("name", "Equipment ID"), CONTRACTOR, SITE, field("category", "Kategori", "select", options=["Excavator", "Dump Truck", "Dozer", "Grader", "Compactor", "Water Truck", "Fuel Truck", "Loader", "Support Equipment"]), field("brand", "Brand / model"), field("serial", "Serial number"), field("capacity", "Kapasitas", "number"), field("ownership", "Kepemilikan", "select", options=["Owned", "Rental"]), field("commission", "Commission date", "date"), field("operating_status", "Status equipment", "select", options=["Working", "Standby", "Breakdown", "Maintenance", "Waiting", "Idle"])], ["name", "contractor_id", "category", "brand", "operating_status"], ["Mining Operation", "Dispatch", *CONTRACTOR_ROLES]),
 "manpower": module("Manpower", "Operations", [DATE, SHIFT, SITE, CONTRACTOR, field("position", "Posisi"), field("planned", "Rencana personel", "number"), field("actual", "Personel hadir", "number"), field("hours", "Total jam kerja", "number")], ["date", "contractor_id", "position", "planned", "actual"], OPS),
 "production": module("Daily production", "Operations", [DATE, SHIFT, SITE, CONTRACTOR, PIT, field("block", "Block"), field("seam", "Seam", required=False), ACTIVITY, field("material", "Material", "select", options=["Overburden", "Coal", "Topsoil", "Other"]), field("loading", "Loading point"), field("dumping", "Dumping point"), EQUIPMENT, QUANTITY, UNIT, field("distance", "Jarak (km)", "number"), field("working", "Working hours", "number"), field("standby", "Standby hours", "number"), field("breakdown", "Breakdown hours", "number"), field("maintenance", "Maintenance hours", "number"), field("scheduled", "Scheduled hours", "number")], ["date", "shift", "contractor_id", "activity", "quantity", "unit", "status"], OPS, ["Contractor Supervisor", "Owner Supervisor"]),
 "stockpiles": module("Stockpile & saldo", "Operations", [field("name", "Nama stockpile"), field("code", "Kode stockpile"), SITE, field("type", "Tipe stockpile", "select", options=["ROM", "Intermediate", "Port", "Jetty"]), field("capacity", "Kapasitas terpasang (ton)", "number"), field("minimum_stock", "Minimum stock (ton)", "number", False), field("opening_balance", "Saldo awal (ton)", "number", False), field("coal_spec", "Coal specification", required=False)], ["name", "code", "type", "capacity", "book_balance", "capacity_utilization", "status"], ["Mine Engineering", "Mining Operation", "Dispatch"]),
 "hauling": module("Coal hauling", "Operations", [DATE, SHIFT, SITE, CONTRACTOR, EQUIPMENT, field("origin_location_id", "Lokasi asal", "reference", ref="locations"), field("destination_stockpile_id", "Stockpile tujuan", "reference", ref="stockpiles"), field("transport_mode", "Moda hauling", "select", options=["Darat", "Sungai", "Laut"]), field("route", "Rute / koridor hauling"), field("distance", "Jarak satu arah (km)", "number"), field("trips", "Jumlah rit / voyage", "number"), field("material", "Material", "select", options=["Coal"]), QUANTITY, field("unit", "Satuan", "select", options=["Ton"]), field("transport_reference", "Nomor DO / surat jalan / bill of lading"), field("carrier", "Unit angkut / tongkang / vessel", required=False)], ["date", "transport_mode", "origin_location_id", "destination_stockpile_id", "distance", "trips", "quantity", "status"], OPS, ["Owner Supervisor"]),
 "stockpile_movements": module("Mutasi stockpile", "Operations", [DATE, SITE, field("stockpile_id", "Stockpile", "reference", ref="stockpiles"), field("direction", "Arah mutasi", "select", options=["IN", "OUT"]), field("movement_type", "Jenis mutasi", "select", options=["Opening Balance", "Manual Addition", "Sale / Shipment", "Transfer Out", "Quality Adjustment", "Shrinkage", "Stock Count Adjustment"]), QUANTITY, field("unit", "Satuan", "select", options=["Ton"]), field("reference", "Referensi ticket / survey / shipment"), field("notes", "Catatan", "textarea", False)], ["date", "stockpile_id", "direction", "movement_type", "quantity", "status"], ["Mining Operation", "Dispatch", "Owner Supervisor"], ["Owner Supervisor"]),
 "surveys": module("Survey & measurement", "Assurance", [DATE, PERIOD, SITE, CONTRACTOR, PIT, field("block", "Block"), ACTIVITY, field("material", "Material", "select", options=["Coal", "Overburden", "Topsoil", "Other"]), field("beginning", "Volume awal", "number"), field("ending", "Volume akhir", "number"), QUANTITY, UNIT], ["date", "contractor_id", "pit_id", "quantity", "status"], ["Surveyor"], ["Surveyor", "Mine Engineering", "Owner Supervisor"]),
 "reconciliations": module("Rekonsiliasi", "Assurance", [SITE, CONTRACTOR, field("production_id", "DPR terverifikasi", "reference", ref="production"), field("survey_id", "Survei final", "reference", ref="surveys"), field("owner_quantity", "Owner quantity", "number"), field("weighbridge", "Weighbridge quantity", "number", False), field("stockpile", "Stockpile quantity", "number", False), field("approved_quantity", "Commercial quantity", "number"), field("resolution", "Investigasi / penyelesaian", "textarea", False)], ["production_id", "survey_id", "variance", "approved_quantity", "status"], ["Surveyor", "Mine Engineering", "Mining Operation"], ["Mine Engineering", "Owner Supervisor", "Commercial"]),
 "fuel": module("Fuel management", "Performance", [DATE, SITE, CONTRACTOR, EQUIPMENT, field("station", "Fuel station"), field("liter", "Liter", "number"), field("hour_meter", "Hour meter", "number"), field("operator", "Operator"), field("fuel_truck", "Fuel truck", required=False), field("reference", "Referensi transaksi")], ["date", "equipment_id", "liter", "hour_meter", "status"], ["Fuel Controller", *CONTRACTOR_ROLES], ["Fuel Controller"]),
 "hse": module("HSE & safety", "Performance", [DATE, SITE, CONTRACTOR, field("type", "Jenis kejadian", "select", options=["Fatality", "LTI", "Medical Treatment", "First Aid", "Near Miss", "Property Damage", "Environmental Incident", "Safety Observation", "Inspection"]), field("location", "Lokasi"), field("description", "Deskripsi", "textarea"), field("action", "Tindakan korektif", "textarea"), field("lost_hours", "Lost hours", "number")], ["date", "contractor_id", "type", "location", "status"], ["HSE", *CONTRACTOR_ROLES], ["HSE", "Mine Manager"]),
 "scorecards": module("Contractor scorecard", "Performance", [PERIOD, SITE, CONTRACTOR, *[field(k, label + " (%)", "number") for k, label in [("production", "Production"), ("equipment", "Equipment"), ("productivity", "Productivity"), ("fuel", "Fuel"), ("hse", "HSE"), ("quality", "Quality"), ("compliance", "Compliance")]], field("evidence", "Bukti penilaian", "textarea")], ["period", "contractor_id", "score", "status"], ["Mining Operation", "Commercial"], ["Mine Manager"]),
 "rules": module("Penalty & incentive", "Commercial", [field("name", "Nama aturan"), SITE, CONTRACTOR, CONTRACT, field("kind", "Jenis", "select", options=["Penalty", "Incentive"]), field("metric", "KPI", "select", options=["production", "equipment", "productivity", "fuel", "hse", "quality", "compliance"]), field("operator", "Kondisi", "select", options=["below", "above"]), field("threshold", "Threshold (%)", "number"), field("percent", "Persentase gross claim (%)", "number")], ["name", "contract_id", "kind", "metric", "percent", "status"], ["Commercial"], ["Mine Manager"]),
 "claims": module("Progress claim", "Commercial", [SITE, CONTRACTOR, CONTRACT, PERIOD, field("reconciliation_id", "Rekonsiliasi approved", "reference", ref="reconciliations"), field("scorecard_id", "Scorecard approved", "reference", False, ref="scorecards"), field("deduction", "Deduction (Rp)", "number"), field("deduction_reason", "Alasan deduction", "textarea", False)], ["name", "contractor_id", "quantity", "gross", "net", "status"], ["Commercial", *CONTRACTOR_ROLES], ["Mining Operation", "Surveyor", "Mine Engineering", "Commercial", "Mine Manager", "Finance"]),
 "invoices": module("Invoice & payment", "Commercial", [field("name", "Nomor invoice"), SITE, CONTRACTOR, field("claim_id", "Claim approved", "reference", ref="claims"), DATE, field("due", "Jatuh tempo", "date"), field("amount", "Nilai invoice (Rp)", "number")], ["name", "contractor_id", "amount", "due", "status"], ["Finance"], ["Finance"]),
}

DEFAULT_SETTINGS = {
 "tolerance": 2, "production_warning": 90, "pa_warning": 85, "fuel_standard": 0.8,
 "fuel_excess": 10, "contract_warning": 80, "expiry_days": 90,
 "weights": {"production": 30, "equipment": 15, "productivity": 15, "fuel": 10, "hse": 15, "quality": 5, "compliance": 10},
 "workflows": {k: v["workflow"] for k, v in CATALOG.items() if v["workflow"]}
}
